name: Validate and test

on:
  pull_request:
  workflow_dispatch: # to trigger manually

permissions:
  contents: read

jobs:
  verify:
    name: Verfiy
    runs-on: Akka-Default
    if: github.event.repository.fork == false
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Cache Coursier
        # https://github.com/coursier/cache-action/releases
        # v6.4.5
        uses: coursier/cache-action@1ff273bff02a8787bc9f1877d347948af647956d

      - name: Cache dependencies
        uses: actions/cache@v4.2.0
        with:
          path: ~/.m2/repository
          key: maven-repo-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-repo-

      - name: Set up JDK 21
        # https://github.com/coursier/setup-action/releases
        # v1.3.5
        uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
        with:
          jvm: temurin:1.21

      - name: Checkout Global Scripts
        uses: actions/checkout@v4
        with:
          repository: akka/github-actions-scripts
          path: scripts

      - name: Setup global resolver
        run: |
          chmod +x ./scripts/setup_global_resolver.sh
          ./scripts/setup_global_resolver.sh

      - name: mvn verify
        run: |-
          mvn verify --no-transfer-progress
